# Generated by Django 4.2.30 on 2026-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_issueimage_issue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueupdate",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="issue_updates/"),
        ),
    ]
